### ISSUE TITLE
Add star indicator to heroes

### ISSUE THREAD

**Issue by lukescammell** [j-a-mercury/dragonsoul-gear#2]
Add a way to specify while star evolution level your hero is. This is useful for calculating how much additional gold you need to get to the next level.

**Comment by juviasuisei** [comment]
Definitely on the roadmap. I'm currently working on getting the base hero stats attached to each hero (only made it through Faith Healer so far) and then I'm going to add the ability for people to mark how many stars their heroes are, what level they are, and what level their skills are. This is all working towards being able to accurately calculate current hero stats. Then I'll add in the ability to mark which enhancements and runes you have active (as well as stars/empowerments/etc.).

All of this is moving towards suggestions of which gear you should go after next, where to farm gear/materials, etc.

**Comment by juviasuisei** [comment]
This is done now. It isn't yet used to calculate gold remaining but you can input stars and even per hero. Closing this since the good part is on another ticket.
